version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: gocrud_app
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3310:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    ports:
      - "8200:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Use 'db' as the hostname instead of 127.0.0.1
      DB_URL: "root:password@tcp(db:3306)/gocrud_app"
